dist: jammy
language: python
python:
  - "3.10"
services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - pytest test/

before_deploy:
  - docker build -t $DOCKER_USERNAME/devops-challenge .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/devops-challenge
  on:
    branch: master
